# Generated by Django 4.1.1 on 2022-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='status',
            field=models.CharField(default='incomplete', max_length=50),
        ),
    ]
